# Extending image
FROM node:carbon

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get -y install autoconf automake libtool nasm make pkg-config git apt-utils

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Versions
RUN npm -v
RUN node -v


COPY /covidupdates/package.json PACKAGE_JSON
COPY /covidupdates/package-lock.json PACKAGE_LOCK_JSON
# Install app dependencies
COPY PACKAGE_JSON /usr/src/app/
COPY PACKAGE_LOCK_JSON /usr/src/app/

RUN npm install

# Bundle app source
COPY . /usr/src/app

# Environment variables
ENV NODE_ENV test

# Main command
CMD [ "npm", "test" ]