# Extending image
FROM node:carbon

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get -y install autoconf automake libtool nasm make pkg-config git apt-utils

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Versions
RUN npm -v
RUN node -v

# Install app dependencies
COPY ./package*.json ./
COPY . ./app

RUN npm install

# Environment variables
ENV NODE_ENV test

# Main command
CMD [ "npm", "test" ]