node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: react-test
    container_name: node
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      - "3001:3001"